name: vprofile-actions
on: workflow_dispatch
env:
  AWS_REGION: us-west-1
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofile-eks
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Maven Test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Sonar Scanner
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run:  sonar-scanner 
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} 
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} 
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} 
            -Dsonar.sources=src/ 
            -Dsonar.java.coveragePlugin=jacoco 
            -Dsonar.java.binaries=target/test-classes/com/ 
            -Dsonar.junit.reportsPath=target/surefire-reports/ 
            -Dsonar.jacoco.reportsPath=target/jacoco.exec 
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml    
            -X


      - name: SonarQube Quality Gate Check
        id: sonarqube-check
        uses: sonarsource/sonarcloud-github-action@master
        timeout-minutes: 5
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} 
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
          SONAR_HOST_URL: https://sonarcloud.io      


  BUILS_AND_PUBLISH:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          daemon: true
          dockerfile: ./Dockerfile
          context: ./
          repository: ${{ env.ECR_REPOSITORY }}
          image: vprofileapp
          tag: latest, ${{ github.run_number }}
          region: ${{ env.AWS_REGION }}
  
  Deploy_to_EKS:
    needs: BUILS_AND_PUBLISH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Kube config file
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: kubectl create secret docker-registry regcred --docker-server=https://$ECR_REGISTRY --docker-username=$ECR_USERNAME --docker-password=$ECR_PASSWORD --docker-email=none

      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
        with:
          chart: ./helm/vprofilecharts
          namespace: default
          values: |
            appImage=${{ secrets.REGISTRY }}/${{ env.ECR_REPOSITORY}}
            appImageTag=${{ github.run_number }}
          stack: vprofilestack
      